site_name: PathBoard
copyright: Copyright &copy; 2022 Lucas RODRIGUEZ. All rights reserved
repo_name: Git repository
repo_url: https://github.com/PathBoard/
theme:
  logo: img/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  font:
    text: Lato
    code: Roboto Mono
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
